name: Deploy to EC2 ASG

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get Public IPs of Running ASG Instances
        run: |
          aws autoscaling describe-auto-scaling-groups \
            --auto-scaling-group-names "${{ secrets.ASG_NAME }}" \
            --query "AutoScalingGroups[0].Instances[*].InstanceId" \
            --output text | tr '\n' ' ' > instance_ids.txt

          for instance in $(cat instance_ids.txt); do
            IP=$(aws ec2 describe-instances --instance-ids $instance \
              --query "Reservations[0].Instances[0].PublicIpAddress" \
              --output text)
            [[ "$IP" != "None" ]] && echo "$IP" >> ec2-ips.txt
          done

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > pingMe.pem
          chmod 600 pingMe.pem

      - name: Deploy to EC2 Instances
        run: |
          while IFS= read -r IP; do
            echo "🚀 Deploying to $IP"
            ssh -o StrictHostKeyChecking=no -i pingMe.pem ubuntu@$IP << 'EOF'
              cd /home/ubuntu/aws_load_balancer_testing
              git pull origin master
              npm install
              pm2 restart node_backend || pm2 start index.js --name node_backend
              pm2 save
            EOF
          done < ec2-ips.txt

      - name: Cleanup SSH Key
        if: always()
        run: rm -f pingMe.pem ec2-ips.txt instance_ids.txt
